### PR TITLE
feat: attempt Cyclopedia

### PR DESCRIPTION
**Pull request by kokekanon**
delte

### CODE REVIEW

**Comment by luanluciano93** [comment]
*[Cyclopedia](https://www.tibiawiki.com.br/wiki/Cyclopedia)

**Comment by kojimhojo** [comment]
Por que o pull request foi fechado? @kokekanon

**Comment by rodrigopaixaorj** [comment]
> Por que o pull request foi fechado? @kokekanon

Erro de percurso 😅
PR restaurado

**Comment by kokekanon** [comment]
> Por que o pull request foi fechado? @kokekanon

I don't know why it was closed, but I had 'charms' ready and a part of 'map,' but something happened with this pull request. 

I won't continue with this PR.

sorry @kojimhojo

**Pull request closed without merging**
